language: android
android:
    components:
        - platform-tools
        - tools
        - build-tools-20.0.0    #Build tool version
        - android-28            #targate api version

        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

        licenses:
            - 'android-sdk-license-.+'
            - 'google-gdk-license-.+'








